name: Build and release sms-service

#on: [push]

on:
  release:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node and NPM Registry
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install run and test
      run: |
        npm install
        npm run build
        npm run test
    - name: npm publish
      run: |
        npm version from-git
        npm publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
